openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/chat/channels/:
    get:
      operationId: listChannels
      description: API endpoint that allows Channels to be viewed
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
          description: ''
      tags:
      - api
  /api/chat/channels/{id}/:
    get:
      operationId: retrieveChannel
      description: API endpoint that allows Channels to be viewed
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this channel.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
          description: ''
      tags:
      - api
  /api/chat/messages/:
    get:
      operationId: listMessages
      description: API endpoint that allows Messages to be viewed.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
          description: ''
      tags:
      - api
  /api/chat/messages/{id}/:
    get:
      operationId: retrieveMessage
      description: API endpoint that allows Messages to be viewed.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
      tags:
      - api
  /api/codes/codes/:
    get:
      operationId: listClasses
      description: API endpoint that allows Channels to be viewed
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Code'
          description: ''
      tags:
      - api
    post:
      operationId: createClasse
      description: API endpoint that allows Channels to be viewed
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
          description: ''
      tags:
      - api
  /api/codes/codes/{id}/:
    get:
      operationId: retrieveClasse
      description: API endpoint that allows Channels to be viewed
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this classe.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
          description: ''
      tags:
      - api
    put:
      operationId: updateClasse
      description: API endpoint that allows Channels to be viewed
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this classe.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateClasse
      description: API endpoint that allows Channels to be viewed
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this classe.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Code'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyClasse
      description: API endpoint that allows Channels to be viewed
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this classe.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Channel:
      type: object
      properties:
        name:
          type: string
          description: Name of the channel
          maxLength: 32
        pk:
          type: integer
          readOnly: true
      required:
      - name
    Message:
      type: object
      properties:
        content:
          type: string
          maxLength: 2000
        author:
          type: object
          properties:
            username:
              type: string
              description: Required. 150 characters or fewer. Letters, digits and
                @/./+/-/_ only.
              pattern: ^[\w.@+-]+\z
              maxLength: 150
            avatar:
              type: string
              description: Avatar of the user
              maxLength: 1
            locale:
              enum:
              - en
              - fr
              type: string
              description: Which language does the user use
            pk:
              type: integer
              readOnly: true
          required:
          - username
        timestamp:
          type: string
          format: date-time
        pk:
          type: integer
      required:
      - content
      - author
      - timestamp
      - pk
    Code:
      type: object
      properties:
        name:
          type: string
          maxLength: 127
        classe_groupe:
          type: string
          maxLength: 15
        prof:
          type: string
          maxLength: 31
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        code:
          type: integer
          description: Le code du cours pour Zoom
        link:
          type: string
          maxLength: 255
        posted:
          type: boolean
      required:
      - name
      - classe_groupe
      - prof
      - start
      - end
      - code
      - link
