# Generated by Django 3.1.3 on 2020-12-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('classe_groupe', models.CharField(max_length=15)),
                ('prof', models.CharField(max_length=31)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('code', models.BigIntegerField(help_text='Le code du cours pour Zoom')),
                ('link', models.CharField(max_length=255)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
    ]
