# Generated by Django 3.1.3 on 2020-12-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='U', help_text='Avatar of the user', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text='Which language does the user use', max_length=2),
        ),
    ]
