# Generated by Django 3.1.3 on 2020-12-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impactchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text='Name of the channel', max_length=32, unique=True, verbose_name='Channel name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the channel should be visible to normal users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(help_text='key to the user model that created the message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(help_text='Key to the channel in which the message was posted', on_delete=django.db.models.deletion.CASCADE, to='impactchat.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(help_text='Content of the message, limited to 2 000 characters.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime at which the message was created, defaults to now'),
        ),
    ]
